        
// BinaryOperator.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class BinaryOperator: CustomStringConvertible {
	
	let type: String
	let `operator`: DeclarableOperator
	let lhsType: String
	let lhs: String
	let rhsType: String
	let rhs: String
	let replacement: Expression
	
	init(_ type: String, _ `operator`: DeclarableOperator, _ lhsType: String, _ lhs: String, _ rhsType: String, _ rhs: String, _ replacement: Expression) {
		self.type = type
		self.`operator` = `operator`
		self.lhsType = lhsType
		self.lhs = lhs
		self.rhsType = rhsType
		self.rhs = rhs
		self.replacement = replacement
	}

	public var description: String {
		"@infix " + type.description + " " + `operator`.description + " " + "( " + lhsType.description + " " + lhs.description + " " + ", " + rhsType.description + " " + rhs.description + " " + ") " + "{ " + replacement.description + " " + "} "
	}
	
}
