        
// Call.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class Call: CustomStringConvertible {
	
	let expression: Expression
	
	init(_ expression: Expression) {
		self.expression = expression
	}

	public var description: String {
		"call " + expression.description + " " + "; "
	}
	
}
