        
// DeclarableOperator.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public enum DeclarableOperator: CustomStringConvertible {
	
	case _plusSign_
	case _hyphen_
	case _asterisk_
	case _slash_
	case _percentSign_
	
	public var description: String {
		switch self {
		case ._plusSign_: return "+"
		case ._hyphen_: return "-"
		case ._asterisk_: return "*"
		case ._slash_: return "/"
		case ._percentSign_: return "%"
		}
	}
	
}
