        
// Function.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class Function: CustomStringConvertible {
	
	let returnType: `Type`
	let name: String
	let parameters: Parameters
	let body: FunctionBodyStatements
	
	init(_ returnType: `Type`, _ name: String, _ parameters: Parameters, _ body: FunctionBodyStatements) {
		self.returnType = returnType
		self.name = name
		self.parameters = parameters
		self.body = body
	}

	public var description: String {
		returnType.description + " " + name.description + " " + "( " + parameters.description + " " + ") " + "{ " + body.description + " " + "} "
	}
	
}
