        
// If.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class If: CustomStringConvertible {
	
	let condition: Expression
	let body: FunctionBodyStatements
	let elseIf: If?
	
	init(_ condition: Expression, _ body: FunctionBodyStatements, _ elseIf: If) {
		self.condition = condition
		self.body = body
		self.elseIf = elseIf
	}
	
	init(_ condition: Expression, _ body: FunctionBodyStatements) {
		self.condition = condition
		self.body = body
		self.elseIf = nil
	}

	public var description: String {
		"if " + condition.description + " " + "{ " + body.description + " " + "} " + (elseIf == nil ? "" : "else " + elseIf!.description + " ")
	}
	
}
