        
// Operator.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public enum Operator: CustomStringConvertible {
	
	case binaryOperator(BinaryOperator)
	case unaryOperator(UnaryOperator)
	
	public var description: String {
		switch self {
		case .binaryOperator(let binaryOperator): return binaryOperator.description
		case .unaryOperator(let unaryOperator): return unaryOperator.description
		}
	}
	
}
