        
// Reference.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public indirect enum Reference: CustomStringConvertible {
	
	case identifier(_ identifier: String)
	case member(_ reference: Reference, _ _underscore_terminal: String, _ identifier: String)
	
	public var description: String {
		switch self {
		case .identifier(let identifier): return identifier 
		case .member(let reference, let _underscore_terminal, let identifier): return reference.description + _underscore_terminal + identifier 
		}
	}
	
}
