        
// Return.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class Return: CustomStringConvertible {
	
	let expression: Expression?
	
	init() {
		self.expression = nil
	}
	
	init(_ expression: Expression) {
		self.expression = expression
	}

	public var description: String {
		"return " + (expression == nil ? "" : expression!.description + " ") + "; "
	}
	
}
