        
// SugarOperator.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public enum SugarOperator: CustomStringConvertible {
	
	case _verticalBar_
	case _94
	case _ampersand_
	case _plusSign_
	case _hyphen_
	case _asterisk_
	case _slash_
	case _percentSign_
	case _tilde_
	
	public var description: String {
		switch self {
		case ._verticalBar_: return "|"
		case ._94: return "^"
		case ._ampersand_: return "&"
		case ._plusSign_: return "+"
		case ._hyphen_: return "-"
		case ._asterisk_: return "*"
		case ._slash_: return "/"
		case ._percentSign_: return "%"
		case ._tilde_: return "~"
		}
	}
	
}
