        
// TopLevelStatement.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public enum TopLevelStatement: CustomStringConvertible {
	
	case `struct`(Struct)
	case function(Function)
	case `operator`(Operator)
	
	public var description: String {
		switch self {
		case .`struct`(let `struct`): return `struct`.description
		case .function(let function): return function.description
		case .`operator`(let `operator`): return `operator`.description
		}
	}
	
}
