        
// Type.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public indirect enum `Type`: CustomStringConvertible {
	
	case basic(_ identifier: String)
	case pointer(_ type: `Type`, _ _asteriskunderscore_: String)
	
	public var description: String {
		switch self {
		case .basic(let identifier): return identifier 
		case .pointer(let type, let _asteriskunderscore_): return type.description + _asteriskunderscore_ 
		}
	}
	
}
