        
// TypeCast.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class TypeCast: CustomStringConvertible {
	
	let type: `Type`
	
	init(_ type: `Type`) {
		self.type = type
	}

	public var description: String {
		"( " + "as " + type.description + " " + ") "
	}
	
}
