        
// Type.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public indirect enum `Type`: CustomStringConvertible {
	
	case basic(_ identifier: String)
	case pointer(_ type: `Type`, _ _underscore_terminal: String)
	
	public var description: String {
		switch self {
		case .basic(let identifier): return identifier 
		case .pointer(let type, let _underscore_terminal): return type.description + _underscore_terminal 
		}
	}
	
}
