        
// UnaryOperator.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class UnaryOperator: CustomStringConvertible {
	
	let type: String
	let `operator`: DeclarableOperator
	let lhsType: String
	let arg: String
	let replacement: Expression
	
	init(_ type: String, _ `operator`: DeclarableOperator, _ lhsType: String, _ arg: String, _ replacement: Expression) {
		self.type = type
		self.`operator` = `operator`
		self.lhsType = lhsType
		self.arg = arg
		self.replacement = replacement
	}

	public var description: String {
		"@unary " + type.description + " " + `operator`.description + " " + "( " + lhsType.description + " " + arg.description + " " + ") " + "{ " + replacement.description + " " + "} "
	}
	
}
