        
// Import.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class Import: CustomStringConvertible {
	
	let library: String
	
	init(_ library: String) {
		self.library = library
	}

	public var description: String {
		"import " + library.description + " " + "; "
	}
	
}
