        
// While.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class While: CustomStringConvertible {
	
	let condition: Expression
	let body: FunctionBodyStatements
	
	init(_ condition: Expression, _ body: FunctionBodyStatements) {
		self.condition = condition
		self.body = body
	}

	public var description: String {
		"while " + condition.description + " " + "{ " + body.description + " " + "} "
	}
	
}
