        
// Call.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class Call: CustomStringConvertible {
	
	let function: String
	let args: Arguments
	
	init(_ function: String, _ args: Arguments) {
		self.function = function
		self.args = args
	}

	public var description: String {
		"call " + function.description + " " + "( " + args.description + " " + ") " + "; "
	}
	
}
