        
// Declaration.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class Declaration: CustomStringConvertible {
	
	let name: String
	let type: `Type`?
	let value: Expression?
	
	init(_ name: String) {
		self.name = name
		self.type = nil
		self.value = nil
	}
	
	init(_ name: String, _ value: Expression) {
		self.name = name
		self.type = nil
		self.value = value
	}
	
	init(_ name: String, _ type: `Type`) {
		self.name = name
		self.type = type
		self.value = nil
	}
	
	init(_ name: String, _ type: `Type`, _ value: Expression) {
		self.name = name
		self.type = type
		self.value = value
	}

	public var description: String {
		"var " + name.description + " " + (type == nil ? "" : ": " + type!.description + " ") + (value == nil ? "" : "= " + value!.description + " ") + "; "
	}
	
}
