        
// Else.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public indirect enum Else: CustomStringConvertible {
	
	case uncdoncitional(_ unconditionalElse: UnconditionalElse)
	case conditional(_ _terminalif_terminal: If)
	
	public var description: String {
		switch self {
		case .uncdoncitional(let unconditionalElse): return unconditionalElse.description 
		case .conditional(let _terminalif_terminal): return _terminalif_terminal.description 
		}
	}
	
}
