        
// Expression.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public indirect enum Expression: CustomStringConvertible {
	
	public enum InfixOperator: String {
		case operator_0 = "|"
		case operator_1 = "^"
		case operator_2 = "&"
		case operator_3 = "=="
		case operator_4 = "!="
		case operator_5 = "<"
		case operator_6 = ">"
		case operator_7 = "<="
		case operator_8 = ">="
		case operator_9 = "+"
		case operator_10 = "-"
		case operator_11 = "*"
		case operator_12 = "/"
		case operator_13 = "%"
		case operator_14 = "->"
		case operator_15 = "."
	}
	
	case infixOperator(InfixOperator, Expression, Expression)
	
	public enum SingleArgumentOperator: String {
		case operator_0 = "<<"
		case operator_1 = ">>"
		case operator_2 = "!"
		case operator_3 = "~"
		case operator_4 = "-"
	}
	
	case singleArgumentOperator(SingleArgumentOperator, Expression)
	
	case leftParenthesis_ExpressionrightParenthesis_(String, Expression, String)
	case integer(String)
	case leftSquareBracket_TyperightSquareBracket_Expression(String, Type, String, Expression)
	case string(String)
	case identifier(String)
	case ExpressionleftParenthesis_ArgumentsrightParenthesis_(Expression, String, Arguments, String)
	case ampersand_Expression(String, Expression)
	case asterisk_Expression(String, Expression)
	case Sizeof(Sizeof)

	public var description: String {
		switch self {
		case .infixOperator(let op, let a, let b): return "(\(a.description) \(op.rawValue) \(b.description))"
		case .singleArgumentOperator(let op, let a): return "(\(op.rawValue) \(a.description))"
		case .leftParenthesis_ExpressionrightParenthesis_(_, let expression, _): return "(" + expression.description + ")"
		case .integer(_): return "integer"
		case .leftSquareBracket_TyperightSquareBracket_Expression(_, let type, _, let expression): return "[" + type.description + "]" + expression.description
		case .string(_): return "string"
		case .identifier(_): return "identifier"
		case .ExpressionleftParenthesis_ArgumentsrightParenthesis_(let expression, _, let arguments, _): return expression.description + "(" + arguments.description + ")"
		case .ampersand_Expression(_, let expression): return "&" + expression.description
		case .asterisk_Expression(_, let expression): return "*" + expression.description
		case .Sizeof(let sizeof): return sizeof.description
		}
	}
	
}
