        
// Parameter.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class Parameter: CustomStringConvertible {
	
	let type: `Type`
	let name: String
	
	init(_ type: `Type`, _ name: String) {
		self.type = type
		self.name = name
	}

	public var description: String {
		type.description + " " + name.description + " "
	}
	
}
