        
// Parameter.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class Parameter: CustomStringConvertible {
	
	let name: String
	let type: `Type`
	
	init(_ name: String, _ type: `Type`) {
		self.name = name
		self.type = type
	}

	public var description: String {
		name.description + " " + ": " + type.description + " "
	}
	
}
